### ISSUE TITLE
Wrong result for minute with getPreviousRunDate()

### ISSUE THREAD

**Issue by rteinze** [dragonmantank/cron-expression#14]
Results for the minute-level are wrong, I think.

It's 23:10:05. 

The expression `* * * * *` with `getPreviousRunDate()->format('H:i:s')` should give 23:10:00 as result. But it gives 23:09:00.

Same with `*/2 * * * *` ==> 23:08:00

**Comment by dragonmantank** [comment]
This is a bit of an odd duck because of the way cron works. Cron runs every minute, but a cron expression is not necessarily run at 0 seconds; an expression can be evaluated a few seconds after cron itself is invoked (especially if you have a large amount of crons to process).

With this in mind, this library evaluates everything at the top of the minute. In this case, because your time is `23:10:05`, we actually round that down to `23:10:00`, since cron expressions can only run with the granularity of the minute. We then go back from there based on the expression, so `* * * * *` subtracts a minute (resulting in 23:09:00), and `*/2 * * * *` goes back 2 steps (resulting in 23:08:00).

As far as I'm concerned, this is as correct as we can get since we cannot actually "run" any quicker than each minute.
