### ISSUE TITLE
Multiple "Day if Month" values including "L" for Last Day of Month

### ISSUE THREAD

**Issue by reichwebconsulting** [dragonmantank/cron-expression#15]
I love this library.  I'm using it to run billing on varying schedules.

I just ran into a situation where one customer needs an invoice generated from the 1st of the month through the 15th of the month, and from the 15th of the month through the last day of the month.  So invoice generation needs to run at the end of the day (for them this is 6:00 PM PST) on the 15 and the last day of the month.  My schedule looks like this: 

0 18 L,15 * *

Unfortunately, it does not look like the "day of the month" supports multiple comma-separated days including "L" for the last day, the way it does numeric days.

If this is a desired feature, I'm happy to try and tackle it.

**Comment by reichwebconsulting** [comment]
Could this be as simple as removing the check for "L" from DayOfMonthField::validate()  on line 112?

    // Validate that a list don't have W or L
    if (strpos($value, ',') !== false && (strpos($value, 'W') !== false)) {
        return false;
    }

**Comment by JosefWinkler** [comment]
Hello

my script calculate all runtimes to $max_date with "day of month" so i think it works fine???

Josef


`$max_date=new DateTime('2020-12-31 23:59:29');
$cron = Cron\CronExpression::factory('0 18 L,15 * *');
$date=null;

while (true)
{
    $date=$cron->getNextRunDate($date);
    if ($date > $max_date) {break;}
    print $date->format('Y-m-d H:i:s l').chr(10);
}
`

`2018-05-15 18:00:00 Tuesday
2018-05-31 18:00:00 Thursday
2018-06-15 18:00:00 Friday
2018-06-30 18:00:00 Saturday
2018-07-15 18:00:00 Sunday
2018-07-31 18:00:00 Tuesday
2018-08-15 18:00:00 Wednesday
2018-08-31 18:00:00 Friday
`

**Comment by JosefWinkler** [comment]
Ups Sorry

ist works only with **mtdowling**/cron-expression fine
with dragonmantank it dosn't work

Josef

**Comment by reichwebconsulting** [comment]
Yeah there is a check in the fork project that makes it not work. I don't
see how removing that check affects anything other than making it work. I
would like to contribute it back if no one thinks it's going to cause an
issue

**Comment by JosefWinkler** [comment]
when i remove the checks it works.

i also change this on line 80 in DayOfMonthField::isStatisfiedBy so i think "LW" = Last WeekDay in Month should be possibel:

`       if (strpos($value, 'W')) {
            // Parse the target day
            $targetDay = substr($value, 0, strpos($value, 'W'));

            if ($targetDay == 'L') {
                $targetDay = $date->format('t');
            }
`

**Comment by dragonmantank** [comment]
Some background on why the checks were changed:

The original codebase (and this fork, up through the 1.x line) actually let a lot of the validations through that were improper (most of the checks were very naive regexes). The validations were tightened up to bring them more in-line with how the stock cronie library works, which is one of the more popular libraries. cronie was chosen due to it's install base as well as it's adherence to a pretty core set of cron functionality.

`L`, and `W`, are not standard entries for cronie. Some packages, like the popular Java library quartz, don't even have support. Support for those are basically added when I can find valid examples of how those are actually implemented in real cron libraries.

`W` cannot be used in a range, which is part of the reason for the structure of the check [here](https://github.com/dragonmantank/cron-expression/blob/3f00985deec8df53d4cc1e5c33619bda1ee309a5/src/Cron/DayOfMonthField.php#L112). In keeping with the [`isSatisfiedBy()` check](https://github.com/dragonmantank/cron-expression/blob/3f00985deec8df53d4cc1e5c33619bda1ee309a5/src/Cron/DayOfMonthField.php#L62) above it, the check is changed to not allow L to be anything but itself. 

If a valid example can be made in how `L` should properly work, either in code for an existing actual cron library (not just a validator) or documentation for a library, I will more than happily change the check.

**Comment by catalystfabricsolutions** [comment]
Okay, I don't think I understood that there was a goal of keeping the schedule syntax compatible with some or all other CRON implementations. I guess my only argument for changing it regardless is that it seems like supporting the proposed syntax for using "L" in a series of date identifiers would not make this CRON implementation incompatible with other implementations, but build on top of what they already support.

Either way, I can get around not having this.  I'll just extend CronExpression into maybe a ```ComoundCronExpression``` class, split the schedule string on ";" to create multiple CronExpressions internally, and return if ```isSatisfiedBy()``` is true for any of the expressions. Then I can have one expression for the 15th of the month, and one expression for the last day of the month.

Thanks!

**Comment by reichwebconsulting** [comment]
I really need this feature ATM so I'm just going to fork your library and make the change I mentioned previously to support multiple values including L

**Comment by revilon1991** [comment]
@dragonmantank 
> If a valid example can be made in how L should properly work, either in code for an existing actual cron library (not just a validator) or documentation for a library, I will more than happily change the check.

I need two dates.
15th and last day of month.
I use an expression `* * 15,L * *` and that didn't work.
