### ISSUE TITLE
Q: Use cron-expression to rotate log files

### ISSUE THREAD

**Issue by theking2** [dragonmantank/cron-expression#170]
in `\cronExpression` I see interfaces for `::isDue()` `::getPreviousRunDate()` and `::getNextRunDate()`. How would I use these to find out if a log file needs to be rotated? Would I need something else like a state variable $lastRunDate?

**Comment by dragonmantank** [comment]
Rotating the logs itself would be outside of the logic of this library, but you could use it to trigger whatever logic you want. You would pick a time of day that you would want to run the check and come up with an appropriate cron expression, and then the library can tell you if the current time matches your expression.

For example, you could use something like `0 * * * *` to run a script every hour to see if a log file has reached a given file size, and then rotate the file.

You could also do something like `0 0 * * *` and run a script to rotate the log file at midnight just because. 

You wouldn't need to store any state since the trigger won't ever be something based on a past or future run date. Even if it's "time based" like just rotate every hour, day, whatever, you'd just trigger based on the expression.

**Comment by theking2** [comment]
Thanks.  but how would it know to rotate based on current time and rotate scheme only. Wouldn't it need to know what the last rotate was? like /var/lib/logrotate/status in logrotate(8)?

I tried this, but no rotate occurs:
```
$cron = new \Cron\CronExpression( '2 * * * *' );
// check if state file exists
$fileInfo = new SplFileInfo( 'file.log.state' );
if( !$fileInfo->isFile() ) {
  touch( 'file.log.state' );
}

// check if log file is due based on state file
$dateTime = new \DateTimeImmutable();
if( $cron->isDue( $dateTime->setTimeStamp( $fileInfo->getCTime() ) ) ) {
  // rotate log file
  touch( $fileInfo->getRealPath() );
  $rotation = ( new Cesargb\Log\Rotation() )
    //  ->compress()
    ->files( 10 )
    ->minSize( 20 )
    ->rotate( 'file.log' );
}
```

**Comment by theking2** [comment]
It would only work if the frequency calling it would be higher than the cron frequency. If I'm not mistaken crontab on unix uses a state file (/var/spool/crontab ?). I've found a work around by indeed store the last rotation in the mtime of a file.
