### ISSUE TITLE
Wrong getNextRunDate() result for complex expression

### ISSUE THREAD

**Issue by quincunx** [dragonmantank/cron-expression#172]
Hi!
`getNextRunDate()` on the complex expression (`3-59/15 6-12 */15 1 2-5`) in the documentation returns `2024-01-01 06:03:00`. But as the 1st of January 2024 is a Monday, it must be excluded.

See also https://crontab.guru/#3-59/15_6-12_*/15_1_2-5

**Comment by dragonmantank** [comment]
This should be correct due to the POSIX rules: https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/utilities/crontab.html

> Finally, if either the month or day of month is specified as an element or list, and the day of week is also specified as an element or list, then any day matching either the month and day of month, or the day of week, shall be matched.

Day of Week and Day of Month are technically mutually exclusive, so the generate an `OR` rule instead of an `AND` rule like the other elements when both are specified. 

In your expression, both Day of Week and Day of Month are listed. `*/15` is expanded to a list of `1,16`, and `2-5` is expanded to `2,3,4,5`.  When comparing it uses the `OR` rules, so both Day of Month and Day of Week parts are checked. 

2024-01-01 is the first day of the month, so will trigger based on the "Days of Month" half of the new `OR` expression.

**Comment by dragonmantank** [comment]
Yeah, it's something not a lot of systems do properly. The worst part is that no one remembers why this decision was made - it was just decided decades ago and is now the "standard."
