### ISSUE TITLE
Allows negative range

### ISSUE THREAD

**Issue by iszmais** [dragonmantank/cron-expression#30]
Please correct me if i am wrong but i guess 5-1 * * * * should not be an valid expression

**Comment by dragonmantank** [comment]
Thanks for the note.

This is definitely a bug, but it looks like it stems from the fact that the Day of Week uses 7 and 0 interchangeably, which is in accordance with the cron standard. So `6-0` is _technically_ valid, since 0 is Sunday, and 7 is also Sunday, so semantically we're saying "Saturday to Sunday".

I'll see if I can figure something out.

**Comment by dragonmantank** [comment]
Digging more into this, this is a bit of an odd one. 

According to Vixie-cron, one of the reference crons that is used for this library, this is a valid range. The "problem" is that it will never match anything, but it does actually pass validation according to that library, and we do the same thing.

* `5-1 * * * *` is valid because all of the numbers are in the minute range
* `510-1 * * * *` is invalid, because `510` is not a valid number

Tested on Ubuntu 19.04 with cron 3.0pl1-128.1ubuntu1.

I think because of that I am going to close this issue, because we operate just like the reference implementation.
