### ISSUE TITLE
how to repeat every 2 week on Wed, Thu, Fri

### ISSUE THREAD

**Issue by keithbox** [dragonmantank/cron-expression#33]
I tried something like,
```
    $now = DateTime::createFromFormat('Y-m-d H:i:s', "2019-02-13 22:00:00");
    $min = $now->format('i');
    $hour = $now->format('H');
    $cronExpression = "$min $hour 13/14 * 3-5";
```

but it seems skilled some days, how to repeat every 2 week on specify weekday/weekend like google calendar?
![cron on google calendar](https://user-images.githubusercontent.com/5440966/52724964-46040780-2feb-11e9-89a8-ebff1f69a058.PNG)

**Comment by dragonmantank** [comment]
Unfortunately this is something out of scope for the cron expression, and something better left for the application. Determining "every X [timeframe]" is very start date dependent, and crons do not really have a concept of something like a start date.

There are ways to abuse the shell handling of a crontab on *nix systems, but that is not something I plan on supporting.

Thanks for the suggestion though!

**Comment by keithbox** [comment]
thanks for your answer, I am a newbie on *nix OS and not familiar with cron job, I just would like to know more, therefore how did the developer dealing with this similar case? I am trying to implement a scheduler for the application server on windows platform, what is your suggestion on PHP/Java/C#?

**Comment by dragonmantank** [comment]
I would suggest storing a "next run time" somewhere, and having a job that just checks that value to see if it needs to run. For example, if you want to run something every 2 weeks:

    $nextRun = new \DateTime();
    $nextRun->add(new \DateTimeInterval('P2W');
    $jobService->setNextRun($nextRun); // This would save the date off to a database or something

Then have your job run daily, and just check that value. If `$today == $nextRunDate`, execute the code, otherwise just exit and wait for tomorrow.

Year is a non-standard cron syntax, so it is not supported by this library as of 2.0. You can easily run things once a year by setting the day and month options, but it's a rare case where you are running things every X years, or setting a cron to run on a specific year/set of years.

**Comment by keithbox** [comment]
thank you for your kindly advise
