### ISSUE TITLE
getNextRunDate 

### ISSUE THREAD

**Issue by lucatacconi** [dragonmantank/cron-expression#53]
hi Mtdowling,

i'm using getMultipleRunDates to extimate crontab next run during a month.
i setup CronExpression in this way:

    $cron = Cron\CronExpression::factory('* * * * 1');

then i tried, just for test, to read next 30 crontab execution with this script part:
>     $row["next_run"] = $cron->getNextRunDate()->format('Y-m-d H:i:s');
>     $row["next_run_lst"] = [];
>     $aRUNs = $cron->getMultipleRunDates(30, date("Y-m-01 00:00:00"), false, true);
>     foreach($aRUNs as $aRUN_key => $aRUN){
>     $row["next_run_lst"][] = $aRUN;
>     }

The result is:
>     Array
>     (
>     [next_run] => 2019-09-09 00:00:00
>     [next_run_lst] => Array
>     (
>     [0] => 2019-09-02 00:00:00
>     [1] => 2019-09-02 00:01:00
>     [2] => 2019-09-02 00:02:00
>     ...

if i modify initial setup with $cron = Cron\CronExpression::factory('0 0 * * 1'); the result is OK.
>     Array
>     (
>     [next_run] => 2019-09-09 00:00:00
>     [next_run_lst] => Array
>     (
>     [0] => 2019-09-02 00:00:00
>     [1] => 2019-09-09 00:00:00
>     [2] => 2019-09-16 00:00:00
>     ...

i think there is something wrong with CronExpression.php -> getRunDate at line 380. It seams it would increment always minutes.

**Comment by dragonmantank** [comment]
So, I'm not actually sure this is an issue. The expressions are being evaluated to what you are requesting.

Your expression is `* * * * 1` evaluates to "Run every minute on Monday", which is why the minute is increment. So you should get the next 30 minutes from the start time. Doing some other checking, that seems in line with other cron implementations.

Changing the expression to `0 0 * * 1` makes it evaluate to "Run at the 0 minute of the 0 hour ever Monday", which locks your time in the second run to `00:00:00`. You will then get the next 30 Mondays as a result. 

Let me know if I'm misunderstanding what you are intending though. I'll leave this issue open for a bit.
