### ISSUE TITLE
Invalid data validated as valid

### ISSUE THREAD

**Issue by codercms** [dragonmantank/cron-expression#6]
For example:
```php
$monthField = new MonthField();
var_dump($monthField->validate('*/123'));
```
Month field: */123 is invalid, but $monthField->validate return true.
The same situation with other fields. Actually you can get an error only when using CronExpression's getNextRunDate method - "Step cannot be greater than total range" .

And why this code cause an exception?
```php
$cron = CronExpression::factory('* * * */12 *');
$cron->getNextRunDate();

// Throws an ErrorException: "range(): step exceeds the specified range"
```

**Comment by dragonmantank** [comment]
Thanks @codercms 

Can you verify which version of the library you are using for the first test? `*/123` should return false on a validation test. 

The second error is a bit more involved. "Month" is a range for 1-12, with 12 elements. When you pass `*` as the range, it gets expanded as 1-12, and then the step is applied. So starting at the first element (1), add the step (12). That results in 13, which is outside of the range of 1-12. 

What you probably expect to happen is that the value "wraps" around the end and goes back to 1. I will see what I can do about this. Thanks!

**Comment by dragonmantank** [comment]
Resolved this with https://github.com/dragonmantank/cron-expression/commit/2ff19fb7c4ad21f593bb541b5b698e266733f50d

I verified that cronie will actually accept a step larger than the range of a field, so that was good.

Steps that generate numbers that are larger than the actual range of a field should now wrap around back to the beginning of the range with the above commit. So `*/123` will now validate as well as generate a correct date for getting next runs, previous runs, or checking if a cron is due.
