### ISSUE TITLE
Expression is valid in crontab.guru but returns as invalid here: `0 1 15 JUL Mon,Wed,Fri`

### ISSUE THREAD

**Issue by abcondas** [dragonmantank/cron-expression#60]
Hi.  The following expression works in crontab.guru but not in dragonmantank:
`0 1 15 JUL Mon,Wed,Fri`
[here are the results from crontab.guru](https://crontab.guru/#0_1_15_JUL_Mon,Wed,Fri) which I believe is correct.

min = 0 
hour = 1
day of month = 15
month = JUL
day of week = Mon,Wed,Fri

I just upgraded from original mtdowling looking to have some bugs corrected (seconds) which have been but my unit test did catch this one bug.  Thanks.

**Comment by dragonmantank** [comment]
Hello @abcondas !

This is due to a bug with casing on the days of the week, if you change it to `MON,WED,FRI` it should work on the v2.x branch. 

There is a fix in `master` that will fix the casing issue so that your expression will work without the modification, and will release before the end of the year.

As a note, `master` will eventually be v3.0.0 because of a change in how we calculate when both a Day of Month and a Day Of Week are supplied, which might be a breaking change for you. If you are interested, you can check out #61 which will have that fix. The new behavior should evaluate just like how crontab.guru would, instead of the current behavior where your expression would only trigger if it's July 15th AND a Monday, Wednesday, or Friday.

**Comment by abcondas** [comment]
Thanks.  I just tried changing the incoming cron expression to uppercase and it fixes the one example above but now breaks the shortcuts: ['@hourly', '@daily', '@weekly', '@monthly', '@annually', '@yearly'].  Just FYI for anyone reading this thread.

**Comment by dragonmantank** [comment]
Good catch, I'll make sure that the shortcuts are similarly case insensitive for ease-of-use, and should be in v3.0.0.

**Comment by dragonmantank** [comment]
This should be fixed as of v3.0.0
