### ISSUE TITLE
Wrong result from "0 0 1/1 * *"

### ISSUE THREAD

**Issue by Xen3r0** [dragonmantank/cron-expression#71]
Cron expression: 0 0 1/1 * *
Reference date: 2020-02-26 11:37:35

With v2.3.0, the `getNextRunDate` method return `2020-03-01 00:00:00` but the right value is `2020-02-27 00:00:00`.

But with master branch, `getNextRunDate` throw a exception: `InvalidArgumentException : Invalid CRON field value 1/1 at position 2`.

I have check my cron expression with crontab.guru and this expression is valid: [https://crontab.guru/#0_0_1/1_*_*](https://crontab.guru/#0_0_1/1_*_*)

Why this expression throw a exception or return a wrong result ?

**Comment by dragonmantank** [comment]
If you notice on Crontab Guru, it mentions that `1/1` is non-standard. Try changing it to `*` or `*/1` which is what I think you mean (run every day) and is more what most crons would expect. 

In 2.3.0 it's giving 2020-03-01 because it sees the range as only being a single value, `1`, and the step as also `1`, so the only date it could return is the first of the month. As for master, it should give the same result, but I've tightened up the validation to more clearly throw out things that _look_ correct but are semantically invalid. I'll do some more digging as to why it's throwing the exception.

**Comment by Xen3r0** [comment]
Ok, thanks, i am looking for fix ngx-cron-editor
