### ISSUE TITLE
Issue with parsing `/` on Minute and Hour field

### ISSUE THREAD

**Issue by dnafication** [dragonmantank/cron-expression#77]
It fails to parse `/` in minute or hour field when you are trying to step the value from a minute or hour field but works when used with range value or *. Following code snippet shows the issue.

```php
$c = Cron\CronExpression::factory ('5/2 * * * *')
// InvalidArgumentException with message 'Invalid CRON field value 5/2 at position 0'
$c = Cron\CronExpression::factory ('5-10/2 * * * *') // Success

$c = Cron\CronExpression::factory ('* 2/3 ? * *')
// InvalidArgumentException with message 'Invalid CRON field value 2/3 at position 1'
$c = Cron\CronExpression::factory ('* */3 ? * *') // Success
```

**Comment by dragonmantank** [comment]
This would be intended. You should not be able to step larger than the given range. While there are some libraries that will wrap around passed the end of a range, most cron libraries do not do this and will stop calculating once they are at the end of a range. With that in mind, this library throws an error if the overall step is to large to begin with, as it is clearer to just say `5 * * * *` rather than `5/2 * * * *`. 

`5/2` basically says "Given the range of 5-5, step 2", which doesn't make sense because you cannot move 2 positions. The same applies to `2/3` - "Given the range of 2-2, step 3". 

You will get the same error if you did `5-6/2`, because the range given is not large enough. Semantically it does not make sense, so an error is thrown.

`5-10/2` and `*/3` are ranges, so they are something you can step over.

**Comment by dnafication** [comment]
Thanks for explanation but (`5/2`) is interpreted as starting from 5 step 2 till end (which could be 59 or 23) example: https://crontab.guru/#5/2_4/2_*_*_*

![image](https://user-images.githubusercontent.com/6381587/82745924-27cfae80-9dcd-11ea-9d8b-430c95d55b2a.png)

I believe it can still be a feature without impacting others like crontab.guru has implemented.
