### ISSUE TITLE
 Class constants should not use 'public'

### ISSUE THREAD

**Issue by crainday** [dragonmantank/cron-expression#82]
Hi:

I received a syntax error while running the extension：

Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /data1/pt/dev/zhaopengju/app/os_loan/vendor/dragonmantank/cron-expression/src/Cron/CronExpression.php on line 29

The source code is as follows：

class CronExpression
{
    public const MINUTE = 0;
    public const HOUR = 1;
    public const DAY = 2;
    public const MONTH = 3;
    public const WEEKDAY = 4;
    public const YEAR = 5;
   ...

}

Class constants should not use access modifiers ? 

hope to get your reply

**Comment by NicoHaase** [comment]
Which PHP version do you use? This is allowed since PHP 7.1

**Comment by dragonmantank** [comment]
As mentioned by @NicoHaase , using visibility identifiers is valid since PHP 7.1, which is the lowest version of PHP that this library supports. PHP support prior to 7.1 was dropped as of the v2.0.0 release, so if you need support for PHP 7.0 or lower you will need to use `dragonmantank/cron-expression:^1.0` instead (with the caveat that release is not maintained and does have a bunch of validation bugs).

If you are on PHP 7.1 or higher, feel free to re-open this issue with the PHP version that you are using.
